name: CI
on:
  workflow_dispatch:
  push: # run on pushes to main (only happens when PRs are merged or admin commits directly to main)
    branches:
    - main
    paths:
    - "src/**"
  pull_request: # run on all PR actions (push, open, reopen)
    paths:
    - "src/**"

env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 7.0.x
  WORKING_DIRECTORY: src
  TESTING_DIRECTORY: src

jobs:
  ci:
    name: CI on windows
    runs-on: windows-latest
    steps:
    - name: 🛒 Checkout
      uses: actions/checkout@v4.1.0
    - name: ✨ Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: 🚚 Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: 🛠️ Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: 🧪 Test
      run: dotnet test "${{ env.TESTING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --verbosity normal --filter 'Category!=local'
