name: Publish
on:
  workflow_dispatch:
  push: # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 7.0.x

jobs:
  deploy:
    name: 🚀 Publish Packages
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: 🛒 Checkout
      uses: actions/checkout@v4.1.1
    - name: ✨ Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: 🚀 Pack
      shell: pwsh
      run: dotnet pack .\src\IDisposableGenerator\IDisposableGenerator.csproj --configuration Release --include-symbols --output .artifacts

    - name: 🚢 Publish to GitHub Packages Nuget Registory
      shell: pwsh
      run: |
        dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name "github" "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        dotnet nuget push ".artifacts\*.nupkg" --api-key ${{ secrets.GPR_PAT }} --source "github" --skip-duplicate
        dotnet nuget push ".artifacts\*.snupkg" --api-key ${{ secrets.GPR_PAT }} --source "github" --skip-duplicate
